# fly.toml app configuration file generated for education-victory on 2024-06-15T18:01:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'education-victory'
primary_region = 'dfw'
console_command = "/code/manage.py shell"

[build]

[deploy]
release_command = "python [manage.py](http://manage.py/) migrate"

[env]
CSRF = "https://*.fly.dev"
DATABASE_URL = "postgres://postgres:b71JGJvwulPbiOf@ev-test-db.flycast:5432"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
ENVIRONMENT = "TEST"
PORT = "8000"
ROOT = "https://ev-test.fly.dev/"
HOST = "ev-test.fly.dev"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"